"""
Batch summary report — generated after a Run Checked queue completes.
Aggregates sprint + deep research findings for every ticker that was run.
"""

from datetime import datetime
from pathlib import Path

from logger import get_logger

log = get_logger(__name__)


def generate_batch_summary(results: list[dict], output_path: str | Path) -> Path:
    out = Path(output_path)
    out.parent.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    rows_html  = "".join(_result_row(r) for r in results)
    cards_html = "".join(_result_card(r) for r in results)

    bullish  = [r for r in results if (r.get("findings") or {}).get("insider_signal") == "bullish"]
    bearish  = [r for r in results if (r.get("findings") or {}).get("insider_signal") == "bearish"]
    with_cip = [r for r in results if (r.get("findings") or {}).get("has_cip")]

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Batch Summary — {ts}</title>
<style>
  :root {{
    --bg:#ffffff;--surface:#f6f8fa;--border:#d0d7de;
    --text:#1f2328;--muted:#656d76;--red:#cf222e;
    --green:#1a7f37;--blue:#0969da;--yellow:#9a6700;
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:14px;color:var(--text);background:var(--bg);line-height:1.6}}
  .page{{max-width:1100px;margin:0 auto;padding:40px 32px}}
  .cover{{border-bottom:3px solid var(--blue);padding-bottom:24px;margin-bottom:32px}}
  .cover-label{{font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:var(--blue);margin-bottom:8px}}
  .cover h1{{font-size:26px;font-weight:700;margin-bottom:6px}}
  .cover .sub{{font-size:14px;color:var(--muted)}}
  .stat-row{{display:flex;gap:24px;margin:20px 0}}
  .stat{{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:14px 20px;flex:1;text-align:center}}
  .stat-num{{font-size:28px;font-weight:700;color:var(--blue)}}
  .stat-label{{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-top:2px}}
  h2{{font-size:17px;font-weight:700;margin:32px 0 12px;padding-bottom:8px;border-bottom:1px solid var(--border)}}
  table{{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:24px}}
  th{{background:var(--surface);text-align:left;padding:8px 12px;font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;border-bottom:2px solid var(--border);color:var(--muted)}}
  td{{padding:8px 12px;border-bottom:1px solid var(--border);vertical-align:top}}
  tr:last-child td{{border-bottom:none}}
  .card{{border:1px solid var(--border);border-radius:8px;margin-bottom:20px;overflow:hidden}}
  .card-head{{background:var(--surface);padding:12px 16px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border)}}
  .card-head strong{{font-size:15px}}
  .card-body{{padding:16px}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:700}}
  .badge-green{{background:#dafbe1;color:var(--green)}}
  .badge-red{{background:#ffebe9;color:var(--red)}}
  .badge-yellow{{background:#fff8c5;color:var(--yellow)}}
  .badge-blue{{background:#ddf4ff;color:var(--blue)}}
  .badge-neutral{{background:var(--surface);color:var(--muted);border:1px solid var(--border)}}
  a{{color:var(--blue);text-decoration:none}}
  a:hover{{text-decoration:underline}}
  footer{{margin-top:60px;padding-top:20px;border-top:1px solid var(--border);font-size:11px;color:var(--muted)}}
</style>
</head>
<body>
<div class="page">

<div class="cover">
  <div class="cover-label">Batch Run Summary</div>
  <h1>Queue Results — {len(results)} ticker(s)</h1>
  <div class="sub">{ts}</div>
</div>

<div class="stat-row">
  <div class="stat"><div class="stat-num">{len(results)}</div><div class="stat-label">Tickers Run</div></div>
  <div class="stat"><div class="stat-num" style="color:var(--green)">{len(bullish)}</div><div class="stat-label">Bullish Insider</div></div>
  <div class="stat"><div class="stat-num" style="color:var(--red)">{len(bearish)}</div><div class="stat-label">Bearish Insider</div></div>
  <div class="stat"><div class="stat-num" style="color:var(--yellow)">{len(with_cip)}</div><div class="stat-label">CIP Confirmed</div></div>
</div>

<h2>Overview Table</h2>
<table>
<thead><tr>
  <th>#</th><th>Ticker</th><th>Quarter</th><th>QoQ%</th>
  <th>Insider</th><th>CIP?</th><th>Facility?</th><th>$$ Found?</th><th>Reports</th>
</tr></thead>
<tbody>{rows_html}</tbody>
</table>

<h2>Detailed Findings</h2>
{cards_html}

<footer>Generated by exogesisdoer batch runner &nbsp;·&nbsp; {ts} &nbsp;·&nbsp; For research purposes only.</footer>
</div>
</body>
</html>"""

    out.write_text(html, encoding="utf-8")
    log.info("Batch summary → %s (%d results)", out, len(results))
    return out


def _result_row(r: dict) -> str:
    f        = r.get("findings") or {}
    sig      = f.get("insider_signal", "—")
    sig_css  = {"bullish": "badge-green", "bearish": "badge-red", "neutral": "badge-neutral"}.get(sig, "badge-neutral")
    pct      = f"+{r['qoq_pct']}%" if r.get("qoq_pct") is not None else "+∞%"
    cip      = "✓" if f.get("has_cip") else "—"
    fac      = "✓" if f.get("has_facility") else "—"
    dol      = "✓" if f.get("has_dollar_amounts") else "—"
    rpt_link = f'<a href="{r["report_url"]}" target="_blank">sprint</a>' if r.get("report_url") else "—"
    deep_link= f' &nbsp;<a href="{r["deep_report_url"]}" target="_blank">deep</a>' if r.get("deep_report_url") else ""
    return f"""<tr>
<td style="color:var(--muted);font-size:12px">{r.get("rank","")}</td>
<td><strong>{_e(r["ticker"])}</strong></td>
<td>{_e(r.get("quarter",""))}</td>
<td style="color:#cf222e;font-weight:700">{pct}</td>
<td><span class="badge {sig_css}">{sig.upper()}</span></td>
<td style="text-align:center">{cip}</td>
<td style="text-align:center">{fac}</td>
<td style="text-align:center">{dol}</td>
<td>{rpt_link}{deep_link}</td>
</tr>"""


def _result_card(r: dict) -> str:
    f       = r.get("findings") or {}
    sig     = f.get("insider_signal", "neutral")
    sig_css = {"bullish": "badge-green", "bearish": "badge-red", "neutral": "badge-neutral"}.get(sig, "badge-neutral")
    net     = f.get("net_insider_value", 0)
    net_str = f"${net/1e6:+.2f}M" if net else "—"
    ppe_q   = ", ".join(f.get("ppe_quarters") or []) or "none"

    items = []
    if f.get("has_dollar_amounts"):
        items.append("Specific dollar amounts found in PP&amp;E footnote — high-confidence facility confirmation.")
    if f.get("has_cip"):
        items.append("Construction-in-progress line items present — active buildout underway.")
    if f.get("has_facility"):
        items.append("Facility descriptions found in 10-Q.")
    if sig == "bullish":
        items.append(f"Net insider buying of {net_str} — bullish confirmation of capex signal.")
    elif sig == "bearish":
        items.append(f"Net insider selling of {net_str} — tempers the bullish read.")
    else:
        items.append(f"Insider activity balanced (net {net_str}).")
    if not items:
        items.append("Insufficient data — manual review recommended.")

    bullets = "".join(f"<li style='margin-bottom:6px'>{b}</li>" for b in items)
    rpt_link  = f'<a href="{r["report_url"]}" target="_blank">Sprint report</a>' if r.get("report_url") else ""
    deep_link = f'&nbsp;·&nbsp;<a href="{r["deep_report_url"]}" target="_blank">Deep research report</a>' if r.get("deep_report_url") else ""

    return f"""<div class="card">
  <div class="card-head">
    <strong>{_e(r["ticker"])} — {_e(r.get("name",""))}</strong>
    <div style="display:flex;gap:8px;align-items:center">
      <span class="badge badge-blue">{_e(r.get("quarter",""))}</span>
      <span class="badge {sig_css}">{sig.upper()}</span>
    </div>
  </div>
  <div class="card-body">
    <ul style="margin-left:16px;line-height:1.9">{bullets}</ul>
    <div style="margin-top:12px;font-size:12px;color:var(--muted)">
      PP&amp;E quarters found: {ppe_q} &nbsp;·&nbsp;
      Buys: {f.get("buy_count",0)} &nbsp;·&nbsp; Sells: {f.get("sell_count",0)}
      {f'&nbsp;·&nbsp;{rpt_link}{deep_link}' if rpt_link or deep_link else ''}
    </div>
  </div>
</div>"""


def _e(s: str) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
