"""
Deep research report — supplemental HTML generated by the "Continue Research"
button. Renders Form 4 insider transactions and 10-Q PP&E footnote findings.
"""

import re as _re
from datetime import datetime
from pathlib import Path

from logger import get_logger

log = get_logger(__name__)


def generate_deep_report(
    ticker: str,
    company_name: str,
    anomaly_quarters: list[str],
    insider_txns: list[dict],
    ppe_analysis: list[dict],
    output_path: str | Path,
) -> Path:
    out = Path(output_path)
    out.parent.mkdir(exist_ok=True)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    buys  = [t for t in insider_txns if t["is_buy"]]
    sells = [t for t in insider_txns if not t["is_buy"]]
    buy_value  = sum(t["total_value"] for t in buys)
    sell_value = sum(t["total_value"] for t in sells)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Deep Research — {ticker}</title>
<style>
  :root {{
    --bg: #ffffff; --surface: #f6f8fa; --border: #d0d7de;
    --text: #1f2328; --muted: #656d76; --red: #cf222e;
    --green: #1a7f37; --blue: #0969da; --yellow: #9a6700;
    --mono: 'JetBrains Mono','Fira Code',monospace;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
         font-size: 14px; color: var(--text); background: var(--bg); line-height: 1.6; }}
  .page {{ max-width: 960px; margin: 0 auto; padding: 40px 32px; }}
  .cover {{ border-bottom: 3px solid var(--blue); padding-bottom: 28px; margin-bottom: 36px; }}
  .cover-label {{ font-size: 11px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase;
                  color: var(--blue); margin-bottom: 8px; }}
  .cover h1 {{ font-size: 28px; font-weight: 700; margin-bottom: 6px; }}
  .cover .subtitle {{ font-size: 15px; color: var(--muted); }}
  h2 {{ font-size: 18px; font-weight: 700; margin: 36px 0 14px; padding-bottom: 8px;
        border-bottom: 1px solid var(--border); }}
  h3 {{ font-size: 11px; font-weight: 700; margin: 18px 0 8px; color: var(--muted);
        text-transform: uppercase; letter-spacing: .06em; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }}
  th {{ background: var(--surface); text-align: left; padding: 8px 12px;
        font-size: 11px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase;
        border-bottom: 2px solid var(--border); color: var(--muted); }}
  td {{ padding: 8px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  .buy-row  {{ background: #dafbe1; }}
  .sell-row {{ background: #ffebe9; }}
  .evidence {{ background: var(--surface); border: 1px solid var(--border); border-radius: 6px;
               padding: 16px; margin: 12px 0; font-size: 13px; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700; }}
  .badge-green  {{ background: #dafbe1; color: var(--green); }}
  .badge-red    {{ background: #ffebe9; color: var(--red); }}
  .badge-blue   {{ background: #ddf4ff; color: var(--blue); }}
  .badge-yellow {{ background: #fff8c5; color: var(--yellow); }}
  .signal-box {{ border-radius: 6px; padding: 16px 20px; margin: 20px 0; }}
  .signal-bullish {{ background: #dafbe1; border: 1px solid #82e09a; }}
  .signal-bearish {{ background: #ffebe9; border: 1px solid #ff8182; }}
  .signal-neutral {{ background: var(--surface); border: 1px solid var(--border); }}
  .mono {{ font-family: var(--mono); font-size: 12px; }}
  .empty {{ color: var(--muted); font-style: italic; padding: 12px 0; }}
  ul {{ margin: 8px 0 0 20px; line-height: 1.8; }}
  footer {{ margin-top: 60px; padding-top: 20px; border-top: 1px solid var(--border);
            font-size: 11px; color: var(--muted); }}
</style>
</head>
<body>
<div class="page">

<div class="cover">
  <div class="cover-label">Deep Research — Supplemental Report</div>
  <h1>{company_name} ({ticker})</h1>
  <div class="subtitle">Insider Transactions &amp; 10-Q PP&amp;E Analysis &nbsp;·&nbsp; {generated_at}</div>
  <div style="margin-top:12px;font-size:13px;color:var(--muted)">
    Anomaly quarters: <strong style="color:var(--text)">{", ".join(anomaly_quarters)}</strong>
  </div>
</div>

<h2>1. Insider Transactions (Form 4)</h2>
{_insider_section(insider_txns, buys, sells, buy_value, sell_value)}

<h2>2. PP&amp;E Footnote Analysis (10-Q / 10-K)</h2>
{_ppe_section(ppe_analysis)}

<h2>3. Research Summary</h2>
{_summary_section(ticker, company_name, anomaly_quarters, insider_txns, buys, sells, buy_value, sell_value, ppe_analysis)}

<footer>
  Generated by exogesisdoer deep research module &nbsp;·&nbsp; {generated_at} &nbsp;·&nbsp;
  Source data: SEC EDGAR Form 4, 10-Q/10-K (public) &nbsp;·&nbsp;
  This report is for research purposes only and does not constitute investment advice.
</footer>

</div>
</body>
</html>"""

    out.write_text(html, encoding="utf-8")
    log.info("Deep research report → %s (%d bytes)", out, len(html))

    net = buy_value - sell_value
    findings = {
        "insider_signal":    "bullish" if net > 500_000 else ("bearish" if net < -500_000 else "neutral"),
        "net_insider_value": net,
        "buy_count":         len(buys),
        "sell_count":        len(sells),
        "has_cip":           any(pa.get("cip_items") for pa in ppe_analysis),
        "has_facility":      any(pa.get("facility_descriptions") for pa in ppe_analysis),
        "has_dollar_amounts":any(pa.get("dollar_amounts") for pa in ppe_analysis),
        "ppe_quarters":      [pa["quarter"] for pa in ppe_analysis if pa.get("filing_date")],
    }
    return out, findings


def _insider_section(txns, buys, sells, buy_value, sell_value) -> str:
    if not txns:
        return '<p class="empty">No Form 4 insider transactions found in the window around anomaly quarters.</p>'

    # Signal assessment
    net = buy_value - sell_value
    if net > 500_000:
        sig_class = "signal-bullish"
        sig_text  = f"<strong>Bullish signal</strong> — net insider buying of ${net/1e6:.1f}M. Insiders were buying around the capex spike."
    elif net < -500_000:
        sig_class = "signal-bearish"
        sig_text  = f"<strong>Bearish context</strong> — net insider selling of ${abs(net)/1e6:.1f}M. Heavy selling near the capex spike warrants caution."
    else:
        sig_class = "signal-neutral"
        sig_text  = f"Neutral — balanced buying/selling (net ${net/1e6:+.1f}M). No strong insider conviction signal."

    rows = ""
    for t in sorted(txns, key=lambda x: x["transaction_date"], reverse=True):
        css   = "buy-row" if t["is_buy"] else "sell-row"
        badge = f'<span class="badge badge-green">BUY</span>' if t["is_buy"] else f'<span class="badge badge-red">SELL</span>'
        val   = f"${t['total_value']/1e6:.2f}M" if t["total_value"] >= 100_000 else f"${t['total_value']:,.0f}"
        shares = f"{t['shares']:,.0f}" if t["shares"] else "—"
        price  = f"${t['price_per_share']:.2f}" if t["price_per_share"] else "—"
        rows  += f"""<tr class="{css}">
<td>{t['transaction_date']}</td>
<td>{_esc(t['filer_name'])}</td>
<td style="color:var(--muted);font-size:12px">{_esc(t['filer_title'])}</td>
<td>{badge} <span class="mono" style="font-size:11px">{t['transaction_code']}</span></td>
<td class="mono">{shares}</td>
<td class="mono">{price}</td>
<td class="mono"><strong>{val}</strong></td>
<td style="font-size:11px;color:var(--muted)">{t['quarter']}</td>
</tr>"""

    stats = f"""<div style="display:flex;gap:24px;font-size:13px;margin-bottom:16px">
<div>Total buys: <strong style="color:var(--green)">{len(buys)} transaction(s) / ${buy_value/1e6:.2f}M</strong></div>
<div>Total sells: <strong style="color:var(--red)">{len(sells)} transaction(s) / ${sell_value/1e6:.2f}M</strong></div>
</div>"""

    return f"""<div class="signal-box {sig_class}">{sig_text}</div>
{stats}
<table>
<thead><tr><th>Date</th><th>Filer</th><th>Title</th><th>Type</th><th>Shares</th><th>Price</th><th>Value</th><th>Quarter</th></tr></thead>
<tbody>{rows}</tbody>
</table>"""


def _ppe_section(ppe_analysis) -> str:
    if not ppe_analysis:
        return '<p class="empty">No PP&amp;E analysis available.</p>'

    parts = []
    for pa in ppe_analysis:
        if not pa["filing_date"]:
            parts.append(f'<p class="empty">{pa["quarter"]}: {pa["summary"]}</p>')
            continue

        dollar_html = ""
        if pa["dollar_amounts"]:
            items = "".join(f'<li style="margin-bottom:6px">{_esc(s[:300])}</li>' for s in pa["dollar_amounts"])
            dollar_html = f'<div style="margin-top:12px"><strong>Dollar amounts in PP&amp;E context:</strong><ul style="margin:8px 0 0 16px">{items}</ul></div>'

        cip_html = ""
        if pa["cip_items"]:
            items = "".join(f'<li style="margin-bottom:6px">{_esc(s[:300])}</li>' for s in pa["cip_items"])
            cip_html = f'<div style="margin-top:12px"><strong>Construction in progress:</strong><ul style="margin:8px 0 0 16px">{items}</ul></div>'

        facility_html = ""
        if pa["facility_descriptions"]:
            items = "".join(f'<li style="margin-bottom:6px">{_esc(s[:300])}</li>' for s in pa["facility_descriptions"][:4])
            facility_html = f'<div style="margin-top:12px"><strong>Facility descriptions:</strong><ul style="margin:8px 0 0 16px">{items}</ul></div>'

        commitment_html = ""
        if pa["commitment_sentences"]:
            items = "".join(f'<li style="margin-bottom:6px">{_esc(s[:300])}</li>' for s in pa["commitment_sentences"][:3])
            commitment_html = f'<div style="margin-top:12px"><strong>Capital commitments:</strong><ul style="margin:8px 0 0 16px">{items}</ul></div>'

        form_link = f'<span class="mono" style="color:var(--muted);font-size:11px">{pa["form_type"]} filed {pa["filing_date"]} ({pa["accession"]})</span>'
        parts.append(f"""<div class="evidence">
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px">
  <strong>{pa["quarter"]}</strong> &nbsp; {form_link}
</div>
<div style="font-size:13px;color:var(--text);font-style:italic">{_esc(pa["summary"][:300])}</div>
{dollar_html}{cip_html}{facility_html}{commitment_html}
</div>""")

    return "".join(parts)


def _summary_section(ticker, name, quarters, txns, buys, sells, buy_value, sell_value, ppe_analysis) -> str:
    bullets = []

    # Insider signal
    net = buy_value - sell_value
    if not txns:
        bullets.append("No insider transaction data found — check EDGAR Form 4 filings manually.")
    elif net > 500_000:
        top_buyer = max(buys, key=lambda t: t["total_value"]) if buys else None
        buyer_str = f" (largest: {top_buyer['filer_name']}, ${top_buyer['total_value']/1e6:.1f}M)" if top_buyer else ""
        bullets.append(f"Net insider buying of ${net/1e6:.1f}M{buyer_str} — bullish confirmation of the capex signal.")
    elif net < -500_000:
        bullets.append(f"Net insider selling of ${abs(net)/1e6:.1f}M — insiders were distributing shares near the capex spike. Tempers the bullish read.")
    else:
        bullets.append(f"Insider activity roughly balanced (net ${net/1e6:+.1f}M) — no strong directional signal.")

    # PP&E findings
    for pa in ppe_analysis:
        if pa["dollar_amounts"]:
            bullets.append(f"{pa['quarter']} 10-Q: Specific dollar amounts found in PP&amp;E context — see Section 2 for detail.")
        elif pa["cip_items"]:
            bullets.append(f"{pa['quarter']} 10-Q: Construction in progress line items found — facility buildout is actively underway.")
        elif pa["facility_descriptions"]:
            bullets.append(f"{pa['quarter']} 10-Q: Facility descriptions found — cross-reference with capex spike to confirm scope.")
        elif pa["filing_date"]:
            bullets.append(f"{pa['quarter']} 10-Q filed {pa['filing_date']} — minimal PP&amp;E detail found; may require manual review of full filing.")

    if not bullets:
        bullets.append("Insufficient data to draw conclusions — manual review recommended.")

    items = "".join(f"<li>{b}</li>" for b in bullets)
    return f"""<ul style="line-height:1.9">{items}</ul>
<p style="margin-top:16px;color:var(--muted);font-size:13px">
  Next: cross-reference the PP&amp;E footnote dollar amounts with the CapEx XBRL values to confirm the spike
  is tied to a specific asset addition, then check the asset's expected useful life for timing clues.
</p>"""


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
